### ISSUE TITLE
openssl: certificate validation of broken certificate is successful

### ISSUE THREAD

**Issue by PascalWithopf** [rsyslog/librelp#124]
Steps to reproduce:

* configure librelp with ```--enable-tls-openssl```
* execute test ```tls-basic-brokencert.sh```

The certificate validation will be successful and therefor the test will fail.

**Comment by alorbach** [comment]
Tried to reproduce. Commit 199797e3e6056ac00313e90d580323a101161485  tried to get output of startup_receiver into "error.out.log". However this fails as "startup_receiver" is hardcoded to pipe the output into "librelp.out.log".  This needs to be fixed in the test-framework.sh or changes from commit 199797e3e6056ac00313e90d580323a101161485 need to be reserved. 

As a result error.out.log is simply empty and check_output_only check doesnt work.
