### ISSUE TITLE
relp 100% cpu - rsyslog stop after start

### ISSUE THREAD

**Issue by Rocco83** [rsyslog/librelp#13]
Hi,

The issue i have faced:
- 100% on rsyslog server with imrelp, and just imrelp ad addiction to the standard debian jessie or debian wheezy configuration.
  But the problem seems to be the client with 1.0.0 librelp installed.

The problem is quite described in the two links below:
http://lists.adiscon.net/pipermail/rsyslog/2013-July/033303.html
http://bugzilla.adiscon.com/show_bug.cgi?id=208

I have tested the patch below, and this won't hit the cpu of the collector.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771218

2 problems:
1) i have not found the patch for librelp elsewhere, can you attach this one to the bug 208 if you think is relevant?
2) is possible to develop a patch for the server, in order to avoid this kind of behavior or at least put warnings on logs?

Thanks,
Daniele

**Comment by lexelby** [comment]
We're running into this problem as well.

The patch in the debian bug you linked to highlights the problem.  Here's what happens:

1. `relpSendqSend()` is called.
2. `relpSendqSend()` enters the `while` loop.
3. `relpSendqSend()` calls `relpSendbufSend()`.
4. `relpSendbufSend()` calls `relpTcpSend()`.
5. `relpTcpSend()` calls either `gnutls_record_send()` or `send()`
    * in my case, it's `gnutls_record_send()`, which ultimately calls `writev()`, which I see in my strace just like [this person](https://stackoverflow.com/questions/28078829/issue-with-relp-tls-and-100-cpu)
    * if TLS isn't enabled, `send()` is called instead.
6. `writev()` or `send()` returns `EAGAIN`
7. `relpTcpSend()` sets the number of bytes written to 0 and returns in either case.
8. `relpSendbufSend()` returns `RELP_RET_PARTIAL_WRITE`.
9. `relpSendqSend()` reacts to `RELP_RET_PARTIAL_WRITE` by *calling relpSendbufSend() again*

It's that last bit that's the problem.  Per POSIX, EAGAIN says "you tried to write to a socket but the operation would block".  You're supposed to try again as this code does -- but not instantly.  Presumably you should wait until the next time `epoll()` or `select()` says you can write to that socket.

Normally, socket code doing this kind of thing will probably just spin a bit, slamming the kernel with `send()` or `writev()` calls until the receiving end has read enough that their kernel has sent ACKs and the sending side's kernel allows more data to be written.  

However, in this case, _both sending and receiving sides are doing the same thing_ since they both use librelp.  If both sides try to write something and hit EAGAIN at the same time, then both will deadlock!  Neither can write because the other hasn't read, and neither is reading because they're hard-looping trying to write.

I see that this issue is 3 years old, but the bug is still present in the code on master.  @rgerhards	any chance we can address this?  I'll try to put together a patch, but my lack of familiarity with the codebase might mean I could miss something.

**Comment by rgerhards** [comment]
I am not sure why this was never worked on - possibly overlooked. I need to dig more into the issue, but unfortunately cannot do right now. A core question to ask is if the code at this point should really be using non-blocking mode (the client part does not!).

**Comment by lexelby** [comment]
Got it.  If you can't work on it, then I'll need to do so and fork internally to solve our current logging problems related to this.  I'll file a PR and look forward to your input when you're available in the future.

> A core question to ask is if the code at this point should really be using non-blocking mode (the client part does not!).

Good question!  I would imagine switching to blocking IO would require a much more significant restructuring than just fixing this bug.  At the very least, `relpSendqSend()` would not have a `while` loop.

**Comment by lexelby** [comment]
BTW, thank you for your quick response!

**Comment by rgerhards** [comment]
> Got it. If you can't work on it, then I'll need to do so and fork internally to solve our current logging problems related to this. I'll file a PR and look forward to your input when you're available in the future.

thx, much appreciated!
 
> A core question to ask is if the code at this point should really be using non-blocking mode (the client part does not!).
> 
> Good question! I would imagine switching to blocking IO would require a much more significant restructuring than just fixing this bug. At the very least, relpSendqSend() would not have a while loop.

Actually, the code has server and client functionality. The server part is non-blocking and the client part is (should be) blocking. So it's not a design change, but maybe an implementation flaw. I don't know it is, but this came up immediately when I read the description.

**Comment by lexelby** [comment]
Interesting.  I assumed that both the client and server use `relpSendqSend()`, but I hadn't verified yet.  That's where my deadlock theory came from.  Is that incorrect?

**Comment by rgerhards** [comment]
I haven't worked on the code for quite a while. To be 100% sure I need to verify that myself by following the call flow. But I think a deadlock between a sender and receiver is pretty unlikely.

In essence, IIRC, the main difference is how the socket is created. The client should do it in a blocking way, the server part not.

Right now I am deep inside a big CI change, so I cannot go away from that for the moment.

**Comment by lexelby** [comment]
Got it, thanks!  No pressure, I'll do the digging.

In any case, deadlock isn't really required to cause the problems we're seeing at Fastly.  Anything can cause a socket to start throwing EAGAIN from a write.  I'll try to catch it next time it happens and see if I can shed some more light on what's going on, and if I find anything, I'll report back.

**Comment by rgerhards** [comment]
> In any case, deadlock isn't really required to cause the problems we're seeing at Fastly. Anything can cause a socket to start throwing EAGAIN from a write. I'll try to catch it next time it happens and see if I can shed some more light on what's going on, and if I find anything, I'll report back.

full ACK! the remote peer seems to be unresponsive, and so this goes into the loop. Maybe one can reproduce it by opening a connection to another instance inside a VM and then suspending that VM. I'd think that this might be the trigger. May be harder to achieve if the server part actually is the culprit, as the window must fill up with acknowledgements, and to do so the client must send quite some data. So hitting the right spot for the suspend may be trickier. Probably this is why it did not came up more pressing.

**Comment by lexelby** [comment]
Adding some notes here, no response needed from you @rgerhards since you're busy.

The client does indeed use blocking I/O.  It uses a separate function call tree entirely and doesn't call `relpSendqSend()` like the server.  It calls `relpSendbufSendAll()` which does a blocking write and will also `poll()` while waiting to write more if it can't send.

Theoretically this doesn't eliminate the possibility of a deadlock.  If both sides are trying to write, the client will be doing blocking write calls and the server will be slamming non-blocking write calls.  Neither is reading, and so neither can write.

I see mentions of timeouts in the client code, and I haven't dug in there.  That might explain why eventually, the server seems to unwedge (minutes later).

In any case, now I'm satisfied with my understanding of what's going on with the server side, so I'm going to proceed with producing my patch to avoid repeatedly calling `writev()`/`send()` after receiving EAGAIN.
